FROM ccr.ccs.tencentyun.com/nijigasaki/azuna:net
# docker build . -f Dockerfile -t ccr.ccs.tencentyun.com/nijigasaki/azuna:net-20241225
RUN apt-get update && apt-get install coreutils moreutils iperf3 bind9-dnsutils tcpdump -y 
